package com.fenmo.expense.controller;

import com.fenmo.expense.dto.*;
import com.fenmo.expense.exception.ApiError;
import com.fenmo.expense.service.ExpenseService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/expenses")
@RequiredArgsConstructor
@Slf4j
@Tag(name = "Expenses", description = "Create and query personal expense entries")
public class ExpenseController {

    private final ExpenseService expenseService;

    // ─── POST /expenses ───────────────────────────────────────────────────────

    @PostMapping
    @Operation(
        summary = "Create a new expense",
        description = """
            Creates an expense entry. Supply an `Idempotency-Key` header (UUID) to make
            this operation safe to retry on network failures or double-clicks.
            Replaying the same key returns the original expense without a duplicate insert.
            """
    )
    @ApiResponses({
        @ApiResponse(responseCode = "201", description = "Expense created (or idempotent replay)"),
        @ApiResponse(responseCode = "400", description = "Validation failed",
            content = @Content(schema = @Schema(implementation = ApiError.class))),
        @ApiResponse(responseCode = "500", description = "Unexpected server error",
            content = @Content(schema = @Schema(implementation = ApiError.class)))
    })
    public ResponseEntity<ExpenseResponse> createExpense(
            @Parameter(description = "UUID generated by the client; stable across retries for the same logical request")
            @RequestHeader(value = "Idempotency-Key", required = false) String idempotencyKey,

            @Valid @RequestBody CreateExpenseRequest request) {

        log.info("POST /expenses category='{}' idempotencyKey='{}'",
                request.getCategory(), idempotencyKey);

        ExpenseResponse response = expenseService.createExpense(request, idempotencyKey);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    // ─── GET /expenses ────────────────────────────────────────────────────────

    @GetMapping
    @Operation(
        summary = "List expenses",
        description = "Returns all expenses sorted newest-first. Optionally filter by category."
    )
    @ApiResponses({
        @ApiResponse(responseCode = "200", description = "List of expenses (may be empty)"),
        @ApiResponse(responseCode = "500", description = "Unexpected server error",
            content = @Content(schema = @Schema(implementation = ApiError.class)))
    })
    public ResponseEntity<List<ExpenseResponse>> listExpenses(
            @Parameter(description = "Filter by category name (case-insensitive). Omit to return all.")
            @RequestParam(required = false) String category,

            @Parameter(description = "Sort order — only 'date_desc' is supported (default behaviour).")
            @RequestParam(required = false) String sort) {

        log.info("GET /expenses category='{}' sort='{}'", category, sort);
        List<ExpenseResponse> expenses = expenseService.listExpenses(category);
        return ResponseEntity.ok(expenses);
    }

    // ─── GET /expenses/summary ────────────────────────────────────────────────

    @GetMapping("/summary")
    @Operation(
        summary = "Get expense summary",
        description = "Returns per-category totals and a grand total across all expenses."
    )
    @ApiResponse(responseCode = "200", description = "Aggregated category breakdown")
    public ResponseEntity<ExpenseSummaryResponse> getSummary() {
        log.info("GET /expenses/summary");
        return ResponseEntity.ok(expenseService.getSummary());
    }
}
